### ISSUE TITLE
Suggestion: embed the timezone geojson data as part of the library

### ISSUE THREAD

**Issue by PaulSonOfLars** [catmullet/tz#1]
As of go 1.16, it is now possible to embed files into the library through the [embed package](https://pkg.go.dev/embed). In the spirit of "batteries included", what would you think of embedding the timezones geojson into the binary itself?

I can understand that this might increase the library size, but it would also significantly improve usage not to need the separate file. 

On a related note; is this file simplified? Would it be possible to minimise it to reduce size? That could improve the embedding tradeoff

Great project btw, thank you!

**Comment by catmullet** [comment]
@PaulSonOfLars, great suggestion. Unfortunately, it is not a simplified file.  Wanted to maintain the highest accuracy possible.  I've been playing with the very idea of embedding it using the embed package.  It hasn't been great because of the compression libraries but as soon as I get that figured out it would be much better.  I tried to embed uncompressed which works but it ended up being a monster at around 500 mb and took way to long to start up. If you have any suggestions on how to overcome this it would be much appreciated.  Thanks for looking over the library and your great suggestion.

**Comment by catmullet** [comment]
Embeded geo json file. with Release [v0.1.0](https://github.com/catmullet/tz/releases/tag/v0.1.0).
